# Generated by Django 3.0.3 on 2020-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_deliverypersonprofile_restaurantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurantName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='restaurantprofile',
            constraint=models.UniqueConstraint(fields=('restaurantName', 'location'), name='unique-restaurants'),
        ),
    ]
