# Generated by Django 3.0.3 on 2020-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200410_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurantName',
            field=models.CharField(default='', help_text='Restaurant Name', max_length=50),
        ),
    ]
