# Generated by Django 3.0.3 on 2020-04-11 20:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200410_0556'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restaurantprofile',
            name='unique-restaurants',
        ),
        migrations.RenameField(
            model_name='restaurantprofile',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisine',
            field=models.CharField(default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='managerEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='managerMobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='managerName',
            field=models.CharField(default='', help_text='Manager Name', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurantMobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='serviceType',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('deliveryPickup', 'Delivery/Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='restaurantprofile',
            constraint=models.UniqueConstraint(fields=('restaurantName', 'city'), name='unique-restaurants'),
        ),
    ]
