# Generated by Django 3.0.5 on 2020-04-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customerreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreviews',
            name='ratings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
