# Generated by Django 3.0.3 on 2020-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200413_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreviews',
            name='reviewSubject',
            field=models.CharField(default='<django.db.models.fields.TextField>', max_length=35),
        ),
    ]
