# Generated by Django 3.0.3 on 2020-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200413_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreviews',
            name='reviewSubject',
            field=models.CharField(default='Review', max_length=35),
        ),
    ]
