# Generated by Django 3.0.5 on 2020-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200413_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='minimumOrder',
            field=models.IntegerField(default=100),
        ),
    ]
