# Generated by Django 3.0.5 on 2020-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200429_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
