# Generated by Django 3.0.3 on 2020-03-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_deliverypersonprofile_restaurantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='default_food.jpg', upload_to='FoodItems/')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItems.FoodNames')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RestaurantProfile')),
            ],
        ),
    ]
