# Generated by Django 3.0.5 on 2020-04-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200412_1536'),
        ('FoodItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Outfordeliveery'), (5, 'Completed')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerProfile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RestaurantProfile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFoodQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('foodItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItems.FoodItemsDescription')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItems.OrdersDescription')),
            ],
        ),
    ]
