# Generated by Django 3.0.5 on 2020-04-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200412_1536'),
        ('FoodItems', '0002_orderfoodquantity_ordersdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodCategories', models.CharField(max_length=30)),
                ('restaurants', models.ManyToManyField(to='users.RestaurantProfile')),
            ],
        ),
        migrations.AddField(
            model_name='fooditemsdescription',
            name='foodCategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FoodItems.FoodCategory'),
        ),
    ]
