# Generated by Django 3.0.5 on 2020-04-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0003_auto_20200412_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdescription',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Outfordelivery'), (5, 'Completed')]),
        ),
    ]
