# Generated by Django 3.0.5 on 2020-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0004_auto_20200413_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='categoryDescription',
            field=models.TextField(default=''),
        ),
    ]
