# Generated by Django 3.0.5 on 2020-04-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_deliverypersonprofile_is_available'),
        ('FoodItems', '0006_auto_20200429_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdescription',
            name='deliveryPerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DeliveryPersonProfile'),
        ),
    ]
