google.maps.__gjsload__('geometry', function(_){var tu=function(a,b){return Math.abs(_.dd(b-a,-180,180))},uu=function(a,b,c,d,e){if(!d){c=tu(a.lng(),c)/tu(a.lng(),b.lng());if(!e)return e=Math.sin(_.Od(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Od(b.lat())),_.Pd(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.I(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Od(a.lat());a=_.Od(a.lng());d=_.Od(b.lat());b=_.Od(b.lng());c=_.Od(c);return _.dd(_.Pd(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},vu=_.n(),wu={containsLocation:function(a,b){var c=_.dd(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var t=l.getAt(m),u=l.getAt((m+1)%q),v=_.dd(t.lng(),-180,180),x=_.dd(u.lng(),-180,180),y=Math.max(v,x);v=Math.min(v,x);(180<y-v?c>=y||c<v:
c<y&&c>=v)&&uu(t,u,c,d,f)<a.lat()&&(g=!g)}return g||wu.isLocationOnEdge(a,b)}};_.Za("PolyGeometry.containsLocation",wu.containsLocation);
wu.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.dd(a.lng(),-180,180),e=b instanceof _.Ti,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,t=0;t<q;++t){var u=l.getAt(t),v=l.getAt((t+1)%m),x=_.dd(u.lng(),-180,180),y=_.dd(v.lng(),-180,180),F=Math.max(x,y),K=Math.min(x,y);if(x=1E-9>=Math.abs(_.dd(x-y,-180,180))&&(Math.abs(_.dd(x-d,-180,180))<=c||Math.abs(_.dd(y-d,-180,180))<=
c)){x=a.lat();y=Math.min(u.lat(),v.lat())-c;var N=Math.max(u.lat(),v.lat())+c;x=x>=y&&x<=N}if(x)return!0;if(180<F-K?d+c>=F||d-c<=K:d+c>=K&&d-c<=F)if(u=uu(u,v,d,f,b),Math.abs(u-a.lat())<c)return!0}return!1};_.Za("PolyGeometry.isLocationOnEdge",wu.isLocationOnEdge);var xu={computeHeading:function(a,b){var c=_.Rd(a),d=_.Sd(a);a=_.Rd(b);b=_.Sd(b)-d;return _.dd(_.Pd(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Za("Spherical.computeHeading",xu.computeHeading);
xu.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.Od(c);var e=_.Rd(a);a=_.Sd(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.J(_.Pd(Math.asin(g)),_.Pd(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Za("Spherical.computeOffset",xu.computeOffset);
xu.computeOffsetOrigin=function(a,b,c,d){c=_.Od(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Rd(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Sd(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.J(_.Pd(g),_.Pd(a))};
_.Za("Spherical.computeOffsetOrigin",xu.computeOffsetOrigin);xu.interpolate=function(a,b,c){var d=_.Rd(a),e=_.Sd(a),f=_.Rd(b),g=_.Sd(b),h=Math.cos(d),k=Math.cos(f);b=xu.Cg(a,b);var l=Math.sin(b);if(1E-6>l)return new _.J(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.J(_.Pd(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Pd(Math.atan2(e,b)))};_.Za("Spherical.interpolate",xu.interpolate);
xu.Cg=function(a,b){var c=_.Rd(a);a=_.Sd(a);var d=_.Rd(b);b=_.Sd(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};xu.computeDistanceBetween=function(a,b,c){c=c||6378137;return xu.Cg(a,b)*c};_.Za("Spherical.computeDistanceBetween",xu.computeDistanceBetween);xu.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.af&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=xu.computeDistanceBetween(a[d],a[d+1],b);return c};
_.Za("Spherical.computeLength",xu.computeLength);xu.computeArea=function(a,b){return Math.abs(xu.computeSignedArea(a,b))};_.Za("Spherical.computeArea",xu.computeArea);xu.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.af&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=xu.dl(c,a[e],a[e+1]);return d*b*b};_.Za("Spherical.computeSignedArea",xu.computeSignedArea);xu.dl=function(a,b,c){return xu.el(a,b,c)*xu.Yl(a,b,c)};
xu.el=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=xu.Cg(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
xu.Yl=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.Rd(d);d=_.Sd(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var yu={decodePath:function(a){for(var b=_.$c(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.J(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Za("PolylineCodec.decodePath",yu.decodePath);
yu.encodePath=function(a){a instanceof _.af&&(a=a.getArray());return yu.wn(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Za("PolylineCodec.encodePath",yu.encodePath);yu.wn=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.$c(a);f<g;++f)e=b?b(a[f]):a[f],yu.ij(e[0]-d[0],c),yu.ij(e[1]-d[1],c),d=e;return c.join("")};yu.ij=function(a,b){yu.xn(0>a?~(a<<1):a<<1,b)};yu.xn=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.z.google.maps.geometry={encoding:yu,spherical:xu,poly:wu};_.r=vu.prototype;_.r.decodePath=yu.decodePath;_.r.encodePath=yu.encodePath;_.r.computeDistanceBetween=xu.computeDistanceBetween;_.r.interpolate=xu.interpolate;_.r.computeHeading=xu.computeHeading;_.r.computeOffset=xu.computeOffset;_.r.computeOffsetOrigin=xu.computeOffsetOrigin;_.Mf("geometry",new vu);});
